version: '3.8'
services:
  batch:
    build: .
    environment: 
      TZ: Asia/Tokyo
    # image: node:18
    tty: true
    ports:
      - "8006:8000"
    volumes:
      - .:/src
    working_dir: /src
    restart: always
    command: node /src/index.js